### PR TITLE
Add: Loki to onprem.logging

### PR DESCRIPTION
**Pull request by nlamirault**
Signed-off-by: Nicolas Lamirault <nicolas.lamirault@gmail.com>

### CODE REVIEW

**Comment by mingrammer** [comment]
It seems not generated by `autogen.sh`. Please add a new node with `autogen.sh`.

Contributing guide: https://github.com/mingrammer/diagrams/blob/master/CONTRIBUTING.md

**Comment by nlamirault** [comment]
@mingrammer i use *autogen.sh* and *round*.
But now i've got some changes into `docs/nodes/onprem.md`

Any idea ?

**Comment by mingrammer** [comment]
Don't mind docs change :). It might be due to the unpredictable order of dict keys.

Thank you for contributing!

**Comment by nlamirault** [comment]
@mingrammer Cool. Thanks for this project.

**Pull request merged**
