### PR TITLE
Add: SVN

### PR DESCRIPTION
**Pull request by ryancheley**
Added SVN as an on premises option for version control

### CODE REVIEW

**Comment by gabriel-tessier** [comment]
@ryancheley 

Thanks for the PR but the icon you add have a green background and it don't render well.
Here an icon which is I think more close to the original one (check the favicon) https://subversion.apache.org/
subversion

Here how it render I put both and the others vcs icons which may help to compare the render.

version_control

And the code to generate the diagrams.

```python
from diagrams import Diagram, Cluster
from diagrams.custom import Custom
from diagrams.onprem.vcs import Git, Github, Gitlab
from urllib.request import urlretrieve


with Diagram("Version control", show=False, filename="version_control", direction="LR"):

    # download the icon image file    
    subversion_url = "https://github.com/mingrammer/diagrams/raw/08817b6ae436dfd0ecdff87a0c32ff7b87560221/resources/onprem/vcs/svn.png"
    subversion_icon = "subversion.png"
    urlretrieve(subversion_url, subversion_icon)
    

    with Cluster("OnPrem"):
        with Cluster("VCS"):
            subversion = Custom("SubVersion", "my_resources/subversion.png")
            subversion_green = Custom("SubVersion", subversion_icon)
            git = Git("Git")
            github = Github("GitHub")
            gitlab = Gitlab("GitLab")

```

**Comment by ryancheley** [comment]
@gabriel-tessier thanks (and sorry about that!) I'll update and resubmit my PR

**Review by gabriel-tessier — COMMENTED** [review]
Thanks for the icon!
I hope it will be merged soon.

**Review by mingrammer — APPROVED** [review]
Sorry for the late. Thank you.

**Pull request merged**
