### PR TITLE
Upgrade for 3.12/3.13

### PR DESCRIPTION
**Pull request by tb102122**

### CODE REVIEW

**Comment by tb102122** [comment]
@mingrammer Do you have an idea when the PR can be approved?

**Comment by DinandDotNet** [comment]
Please, update the quick installation guide to **use python up to 3.11**  to prevent long starts and runaway newbie's.

**Comment by tb102122** [comment]
> Please, update the quick installation guide to **use python up to 3.11** to prevent long starts and runaway newbie's.

Hey @DinandDotNet sorry I am not clear what you are suggesting to be updated and how. Can you add more details please.

**Comment by tb102122** [comment]
@niceman1
@mingrammer 

are you able to approve this MR or is the repo no longer activity maintained?

**Comment by billy-doyle** [comment]
Really want this, seems though based on the activity this project seems to not be actively maintained anymore. Fork time?

**Comment by tb102122** [comment]
> Really want this, seems though based on the activity this project seems to not be actively maintained anymore. Fork time?

Done already
https://pypi.org/project/diagrams-xtd/
https://github.com/diagrams-web/diagrams-xtd

**Review by mingrammer — APPROVED** [review]

**Comment by mingrammer** [comment]
I missed it. Sorry for the late approve.

**Comment by mingrammer** [comment]
I'm not able to work with laptop now. Could you please check the failed tests? https://github.com/mingrammer/diagrams/actions/runs/11713959003/job/32627728019#step:6:1

Thank you.

**Comment by mingrammer** [comment]
New version is now released: https://github.com/mingrammer/diagrams/releases/tag/v0.24.1

**Pull request merged**
