### PR TITLE
feat(node): add Generic OS Red Hat

### PR DESCRIPTION
**Pull request by bdsoha**

### CODE REVIEW

**Comment by gabriel-tessier** [comment]
Hi @bdsoha 

Thanks for your contribution but I expect that you did not read the contributing file:

As written in the contributing file the picture must be maximum 256 pixels.
Here the quote from the contributing file:

> Images should be resized to fit a maximum of 256 pixels wide or high.

According to the commit you updated the generic.md file and added an alias, you should not edit the md file but run autogen.sh
The quote from the file:
> Then just run the ./autogen.sh to generate the added or updated node classes. 

For the alias check the instruction under the **Update Aliases** section.

The full file:
https://github.com/mingrammer/diagrams/blob/master/CONTRIBUTING.md

If you have any problem running the command or get error you can post here.

**Comment by bdsoha** [comment]
@gabriel-tessier Fixed the proportions, won't happen again.

Thanks.

**Comment by mingrammer** [comment]
1,677 files changed? Check is please.

**Comment by bdsoha** [comment]
> 1,677 files changed? Check it please 🤔 .

This is the merged static web files generated since adding the thumbnail.

**Comment by bdsoha** [comment]
The static files are causing some issues.
I am going to close this and reopen on a new branch.

**Pull request closed without merging**
