### PR TITLE
Adding sagemaker resources

### PR DESCRIPTION
**Pull request by leandrodamascena**
image

### CODE REVIEW

**Comment by leandrodamascena** [comment]
Hi @mingrammer . Are you ok?! If you have a free time, could you update pip package?

Our project depends on diagram to draw resources (https://github.com/Cloud-Architects/cloudiscovery).

Thank you.

**Comment by mingrammer** [comment]
Your project, cloudiscovery looks awesome. Great :)

I'll release the next version soon.

**Comment by mingrammer** [comment]
@leandrodamascena Can I add the cloudiscovery in the [Who use it](https://github.com/mingrammer/diagrams#who-use-it) list section?

**Comment by leandrodamascena** [comment]
@mingrammer of course you can!! :D

And thanks for you feedback .. We thank you about diagrams project, it's an important resource in our project!

**Comment by mingrammer** [comment]
Thank you :) And the Diagrams v0.14.0 is now released! Please try with this version.

**Comment by leandrodamascena** [comment]
Nice.. I'll update diagrams version and try!! Thank you!

**Pull request merged**
