### PR TITLE
Add the SQL programing language and the SQLPage framework

### PR DESCRIPTION
**Pull request by lovasoa**
The SQL icon was created by me.

The SQLPage icon is the official one from https://sql.datapage.app/

### CODE REVIEW

**Comment by gabriel-tessier** [comment]
Thanks for the PR,

First as stated in the contributing file the icon must be maximum 256px, yours is 258, and also you need to run autogen script.

You can read all the details about here: about the https://github.com/mingrammer/diagrams/blob/master/CONTRIBUTING.md

About SQL icon it's not that I don't like the icon you created but I quickly searched and found this one, which is a little more modern: 
https://www.vectorstock.com/royalty-free-vector/sql-database-icon-logo-design-ui-or-ux-app-vector-17507753

**Comment by lovasoa** [comment]
The image you linked cannot be distributed under the MIT license of this project. I generated a new, hopefully better looking one; let me know what you think

**Comment by gabriel-tessier** [comment]
@lovasoa Thanks for the icons I will run autogen later this week.

**Review by tvqphuoc01 — APPROVED** [review]

**Comment by lovasoa** [comment]
thanks :100:

**Pull request merged**
