### PR TITLE
GCP IAP (Identity Aware Proxy)

### PR DESCRIPTION
**Pull request by McSly**
Add icon for GCP IAP (Identity Aware Proxy)
See issue #33

### CODE REVIEW

**Comment by mingrammer** [comment]
How did you extract that icon image? It looks blurry, unlike other icon images. (and also it's background is not transparent)

Screen Shot 2020-02-27 at 8 49 29 PM

**Comment by McSly** [comment]
I had a couple of versions for that image and I uploaded the wrong one. New version should be correct

**Comment by mingrammer** [comment]
Looks good. But could you please re-open the PR after cleaning the commit tree?

**Comment by mingrammer** [comment]
I close it. I added you as a co-author for #56. Thank you!

**Pull request closed without merging**
