### PR TITLE
Add Terraform

### PR DESCRIPTION
**Pull request by yu-iskw**
> Terraform is an open-source infrastructure as code software tool created by HashiCorp. It enables users to define and provision a datacenter infrastructure using a high-level configuration language known as Hashicorp Configuration Language (HCL), or optionally JSON.

## NOTE
- `iac` stands for Insrastructure-as-Code.

### CODE REVIEW

**Comment by mingrammer** [comment]
I think the Terraform is not a service or standalone service as a component of system architecture.

**Comment by yu-iskw** [comment]
To some extent, I feel the same. What about the fully-managed Terraform provided by HashiCorp? I think Terraform can be a service.

**Comment by mingrammer** [comment]
Do you mean the [Terraform Cloud](https://www.terraform.io/docs/cloud/index.html)? :)

**Comment by yu-iskw** [comment]
I mean https://www.hashicorp.com/products/terraform.

**Comment by yu-iskw** [comment]
Yes, it is.

**Comment by mingrammer** [comment]
Yap. it make sense :)

**Comment by mingrammer** [comment]
Thank you!

**Comment by yu-iskw** [comment]
Thank you for merging it.

**Pull request merged**
