### PR TITLE
Add: Buzfeed SSO and Oauth2 Proxy

### PR DESCRIPTION
**Pull request by nlamirault**
Signed-off-by: Nicolas Lamirault <nicolas.lamirault@gmail.com>

### CODE REVIEW

**Review by mingrammer — COMMENTED** [review]
I suggest `onprem.auth` or `onprem.identity` category for these services. Reference the [`saas.identity` category](https://diagrams.mingrammer.com/docs/nodes/saas#saasidentity)

**Comment by nlamirault** [comment]
@mingrammer i move into `onprem.auth`. I had chosen network to put these services with Pomerium

**Comment by mingrammer** [comment]
I think pomerium seems fit to the network rather than auth. 

This is a description of pomerium: `Pomerium is an identity-aware proxy that enables secure access to internal...`.

**Comment by nlamirault** [comment]
@mingrammer :+1:

**Review by mingrammer — APPROVED** [review]
LGTM. Thank you.

**Pull request merged**
