### PR TITLE
Add icons to docs

### LINKED ISSUE #466: Please add a demo/example of each Node shape in documentation set
Hi - the documentation is a great start, with the nodes well categorized, but it would be useful to have a visible example of each one along with the name in the browsable docs!

Thank you  - cool project and useful tool with lots of potential.

### PR DESCRIPTION
**Pull request by lrjball**
Thought it could be useful to have an image showing what the icon looks like in the docs. Also fixes #466

This is how the change looks:

diagrams_docs_with_icons

I couldn't decide how to handle the white icons from OCI, so they are currently not visible against the white background, but they all have a black icon alternative next to them which is visible so that shouldn't be much of an issue. Can update this though if there any any suggestions for handling the white icons.

### CODE REVIEW

**Comment by gabriel-tessier** [comment]
Hi, 

just for information there's already an issue about, you can check here: https://github.com/mingrammer/diagrams/issues/78

The issue is pretty old but maybe there's some work in progress.

**Comment by lrjball** [comment]
thanks @gabriel-tessier, I must have missed that issue when I checked. @mingrammer, is this issue being worked on or could this PR help? Don't mind either way, but happy to make changes to this one if needed

**Comment by mdavis-xyz** [comment]
@mingrammer  said they'd do work on #78 , but that was over a year ago.

Given that there are so many duplicate issues raised for this, I believe it's a super valuable contribution. If it works, then we should just merge it.

**Comment by lrjball** [comment]
@mingrammer, does this PR look okay? There are now a couple of merge conflicts which I resolve if this can go in. This seems like a fairly frequently requested feature

**Comment by mingrammer** [comment]
This is an AMAZING contribution. I love it ❤️ @lrjball Please resolve the conflicts, then I'll merge and deploy it.

**Comment by lrjball** [comment]
@mingrammer thanks :smiley:  all conflicts are resolved now, just had to rerun the autogen.sh as new icons had been added since I first made this

**Comment by mingrammer** [comment]
There are many PRs that could be merged at any time. And I merged a PR, there was a conflict with this PR. I request the last update to resolve the conflict 🙏 Thank you!

**Comment by lrjball** [comment]
Okay no worries, should be resolved now

**Comment by bdsoha** [comment]
@mingrammer This closes #78 and #634

**Comment by mingrammer** [comment]
@bdsoha I'll close those. Thank you for addressing it.

**Comment by bdsoha** [comment]
@mingrammer Sorry for the oversight, also #509.

**Comment by mingrammer** [comment]
@bdsoha Thank you!! :D I closed that.

**Comment by mingrammer** [comment]
I announced this feature: https://github.com/mingrammer/diagrams/discussions/777.

**Pull request merged**
