### PR TITLE
Allow custom dot attributes in Diagram constructor

### PR DESCRIPTION
**Pull request by deadmeu**
Allow custom graph, node, and edge attributes to be passed in to the Diagram constructor. This allows the user to configure the output image using whatever configuration of attributes they would like.

### CODE REVIEW

**Comment by mingrammer** [comment]
Could you please provide a practical example use custom options?

Because I want to hide the internal implementation-specific options to users who don't know or even who know the Graphviz.

The `outformat`, `direction` options are also `dot` attributes, but provided as normal arguments. So users don't have to know Graphviz options.

**Comment by deadmeu** [comment]
I was looking to render with a transparent background, though I think providing some mechanism to allow users to customise the rendered image is important.

Since Graphviz is a hard dependency of this project, and there is plenty of documentation available online, I figured it would be ok to allow users to pass in their own Graphviz configuration.

**Comment by deadmeu** [comment]
Thanks, I really hate drawing diagrams using popular visual editors, so the natural language expression using python, along with the awesome pre-provided icons, intrigues me.

I found the changes in this PR to be quite compelling in being able to rapidly prototype the design. Take a look: https://streamable.com/f9zf1

Maybe as a future edition we could develop something like a `DiagramOptions` class, decoupling the Graphviz attributes from Diagrams? That way, we would only need to pass in a single `options` parameter into the constructor of the `Diagrams` class which would contain all of the configuration, including the existing `outformat` and `direction` options. I'm not very experienced with Python though so there may be a more Pythonic way to handle this.

**Comment by mingrammer** [comment]
Wow! I'm glad to see that someone makes a demo video using a library I made :) Thank you.

The idea of `DiagramOptions` class sounds good to me. We can more develop this idea. I'm willing to support option class in the future. (while keeping the backward compatibility)

**Pull request merged**
