### PR TITLE
🔥 Removed support for Python 3.6

### PR DESCRIPTION
**Pull request by bdsoha**
Related #855

### CODE REVIEW

**Comment by bdsoha** [comment]
@mingrammer Any chance you can merge this PR? Thanks in advance.

*P.S. `Python 3.7` is EOL by June 27, 2023*.

**Comment by mingrammer** [comment]
Please rebase with master :)

**Comment by bdsoha** [comment]
> Please rebase with master :)

Done

**Comment by bdsoha** [comment]
> Please rebase with master :)

@mingrammer Done, any change to merge?

**Review by mingrammer — APPROVED** [review]

**Pull request merged**
