### PR TITLE
feat: add azure private endpoint node

### PR DESCRIPTION
**Pull request by pisethdanh**
@mingrammer please review when you have some time.

### CODE REVIEW

**Comment by nreisbeck** [comment]
Bumping this PR as I'm very interested in being able to use Azure Private Endpoints :+1:

**Comment by ebbypeter** [comment]
Waiting for this PR to be merged... Is there anything blocking this?

**Comment by ebbypeter** [comment]
@mingrammer Lack of this is stopping me from using Diagram in my org. Are there any comments / updates that needs to be done on this PR?

**Comment by mingrammer** [comment]
@ebbypeter Sorry for late reply. I'll check it soon (in 12h)

**Review by mingrammer — APPROVED** [review]

**Comment by mingrammer** [comment]
https://github.com/mingrammer/diagrams/releases/tag/v0.23.4 is now released.

**Comment by ebbypeter** [comment]
Thanks @mingrammer :)

**Pull request merged**
