### PR TITLE
feat(node): Add Zendesk

### PR DESCRIPTION
**Pull request by GDS-Dominic**
Added Zendesk as a SaaS solution.

- I have created a `crm` subdirectory for future related SaaS offerings as I don't believe Zendesk fitted in the existing directories, this could alternatively be renamed to something like `support`
- The current logo does have text in, if needed I can change to a logo without.

### CODE REVIEW

**Review by ingcrengifo — APPROVED** [review]

**Review by hussani — APPROVED** [review]

**Comment by tvqphuoc01** [comment]
Hi, @GDS-Dominic You can read all the details here: the https://github.com/mingrammer/diagrams/blob/master/CONTRIBUTING.md to contribute to this project thank you 🚀 please run the script to auto-gen the website static file also 📁

**Review by gabriel-tessier — CHANGES_REQUESTED** [review]
Need to run autogen the website icon is missing

**Review by filipeaaoliveira — APPROVED** [review]

**Comment by tvqphuoc01** [comment]
Hi guys, seems like the owner of this branch is no longer maintaining this code so I will close this one and create another PR to update Zendesk. Thank you 👨‍💻

**Comment by tvqphuoc01** [comment]
Hi guys, seems like the owner of this branch is no longer maintaining this code so I will close this one and create another PR to update Zendesk. Thank you 👨‍💻

**Comment by tvqphuoc01** [comment]
https://github.com/mingrammer/diagrams/pull/1072

**Pull request closed without merging**
