### PR TITLE
Added more generic icons #126

### PR DESCRIPTION
**Pull request by leandrodamascena**
image

### CODE REVIEW

**Comment by mingrammer** [comment]
How about [this](https://developer.android.com/distribute/marketing-tools/brand-guidelines?hl=ko#android_robot) for android logo?

**Comment by leandrodamascena** [comment]
you mean it?

image

**Comment by mingrammer** [comment]
Ye. That is a new brand logo of Android.

**Comment by leandrodamascena** [comment]
Ok ok.. let me fix it...

**Comment by leandrodamascena** [comment]
image

**Pull request merged**
