### PR TITLE
Add: new component Beats from Elasticstack

### PR DESCRIPTION
**Pull request by nlamirault**
Signed-off-by: Nicolas Lamirault <nicolas.lamirault@gmail.com>

### CODE REVIEW

**Comment by mingrammer** [comment]
It doesn't seem to have been generated via autogen.sh. Please run the autogen.sh to add the new node class.

**Comment by nlamirault** [comment]
@mingrammer it has been generated using autogen.sh but i forgot to push the *docs* directory.

**Comment by mingrammer** [comment]
Resolve the conflicts please.

**Comment by nlamirault** [comment]
@mingrammer done.

**Comment by mingrammer** [comment]
We started support the `elastic` provider. Could you please move the `Beats` under `elastic.elasticsearch`? Thank you.

Ref: https://diagrams.mingrammer.com/docs/nodes/elastic

**Comment by nlamirault** [comment]
@mingrammer Done. I move beats into same directory as Kibana.

**Pull request merged**
