### PR TITLE
Add: Cloud native storage

### PR DESCRIPTION
**Pull request by nlamirault**
- https://rook.io/
- https://openebs.io/
- https://min.io

### CODE REVIEW

**Comment by nlamirault** [comment]
What do you think about move into `k8s.storage` ? Like for #297 and `k8s.chaos`

**Comment by nlamirault** [comment]
@mingrammer `k8s.storage` already exists.

What do you think about create this : 

```
❯ tree k8s 
  k8s
└──   echosystem
   ├──   chaos
   ├──   storage
   └──   tools
   ...
```

**Comment by mingrammer** [comment]
Hm , I think the `minio` is not for **only** k8s. (of course, rook and openebs looks fit in this category.)

\+ `k8.ecosystem.<subcategory>` looks good to me too. Maybe, we need to some extra work to support multi-depth categories when generating nodes.

**Comment by nlamirault** [comment]
See #342

**Pull request closed without merging**
