### PR TITLE
Support Apache Beam

### PR DESCRIPTION
**Pull request by yu-iskw**
https://github.com/apache/beam

## Reference
- https://beam.apache.org/community/logos/

### CODE REVIEW

**Comment by mingrammer** [comment]
Could you please more clean image? You can find it at https://www.vectorlogo.zone/logos/apache_beam/index.html

**Comment by yu-iskw** [comment]
@mingrammer Thank you for the feedback. I don't completely understand what you mean. What do you mean by more cleaner? The SVG image looks same as the three color version in the beam's web page. The PNG file I pushed is resized to 256x256 from the full color version.

**Comment by mingrammer** [comment]
Oh sorry, I misread the image. LGTM :)

**Comment by yu-iskw** [comment]
Thank you for reviewing it!

**Pull request merged**
