### PR TITLE
Add: container runtimes

### PR DESCRIPTION
**Pull request by nlamirault**
For: 
- https://containerd.io/
- https://cri-o.io/
- https://gvisor.dev/
- https://firecracker-microvm.github.io/

### CODE REVIEW

**Comment by wolfspyre** [comment]
Neat!

**Review by mingrammer — COMMENTED** [review]
The firecracker logo looks a little small. Please size it up! (reduce white background portion)

**Comment by nlamirault** [comment]
@mingrammer done.

**Review by mingrammer — APPROVED** [review]
LGTM

**Pull request merged**
