### PR TITLE
Adding Presto, Apache Superset, Nextcloud Nodes

### PR DESCRIPTION
**Pull request by llmuculusll**
Adding Presto node to onperm.analytics
PrestoSQL and PrestoDB Logo are exactly same.

### CODE REVIEW

**Comment by llmuculusll** [comment]
also adding Apache superset

**Review by Mvaxtuan16V — APPROVED** [review]

**Comment by llmuculusll** [comment]
adding nextcloud node

**Comment by wolfspyre** [comment]
Cool!  Might want to change the PR title to reflect the other additions? Regardless, this is cool.

**Comment by llmuculusll** [comment]
I edited the title.

**Comment by llmuculusll** [comment]
any plan for merging this pull request?

**Review by mingrammer — APPROVED** [review]
LGTM

**Pull request merged**
