### PR TITLE
Add: External DNS component

### PR DESCRIPTION
**Pull request by nlamirault**
For: https://github.com/kubernetes-sigs/external-dns

### CODE REVIEW

**Review by mingrammer — COMMENTED** [review]
I think it should be placed under `k8s.ecosystem`. (ref: https://diagrams.mingrammer.com/docs/nodes/k8s#k8secosystem)

What do you think about it?

**Comment by nlamirault** [comment]
@mingrammer LGTM. I update the PR.

**Review by mingrammer — CHANGES_REQUESTED** [review]
You should delete onprem/dns.py file.

**Review by mingrammer — APPROVED** [review]
LGTM

**Pull request merged**
