### PR TITLE
Delete Gitpitch from README

### PR DESCRIPTION
**Pull request by gliptak**
https://gitpitch.github.io/gitpitch/#/free-trial
```
GitPitch is shutting down on March 1, 2021. The trial software is no longer available for download.
````

### CODE REVIEW

**Comment by gliptak** [comment]
@mingrammer please approve workflow run

**Comment by mingrammer** [comment]
You can reopen it.

**Comment by gliptak** [comment]
@mingrammer reopen button is disabled for me

**Comment by mingrammer** [comment]
@gliptak The forked repository seems to have been deleted.

**Pull request closed without merging**
