### PR TITLE
Add Erlang and Elixir icons

### LINKED ISSUE #273: Add Erlang and Elixir programming language icons
Add icons for Erlang and Elixir, programming languages that target the BEAM.

### PR DESCRIPTION
**Pull request by DaniruKun**
Closes #273

### CODE REVIEW

**Review by mingrammer — CHANGES_REQUESTED** [review]
There is an alpha background mark on the elixir logo file. How about using [this version](https://www.vectorlogo.zone/logos/elixir-lang/index.html)? 

And we prefer the logo-only image file :)

**Comment by mingrammer** [comment]
The uploaded elixir image is so blurred. Check it, please.

image

**Comment by DaniruKun** [comment]
Updated with higher density ver.

**Review by mingrammer — APPROVED** [review]
LGTM! Thank you.

**Pull request merged**
