### PR TITLE
Add EMQX as an On-Prem Queue entry

### PR DESCRIPTION
**Pull request by Nosferatu31**

### CODE REVIEW

**Comment by Nosferatu31** [comment]
@mingrammer I hope I did follow the community guidelines :)

**Comment by mingrammer** [comment]
The icon looks too small. (120x120) Could you please replace it with 256x256 size?

**Comment by mingrammer** [comment]
And resolve the conflict please.

**Comment by Nosferatu31** [comment]
@mingrammer about the icon size: that was the largest I could find from EMQ. I will check with them again.

**Comment by Nosferatu31** [comment]
@mingrammer done.

**Review by mingrammer — APPROVED** [review]
LGTM!

**Comment by mingrammer** [comment]
Thank you :D

**Pull request merged**
