### PR TITLE
generate tableau and metabase nodes

### PR DESCRIPTION
**Pull request by fellipewurthmann**
generate new nodes for visualization tools: tableau and metabase

### CODE REVIEW

**Comment by fellipewurthmann** [comment]
Hello! @mingrammer 
The project is wonderful,
I use it to build new diagrams for the AWS data pipeline of my work and for that I needed to generate new tableau and metabase nodes! that was amazing!!! Thank you

**Comment by mingrammer** [comment]
Please resolve the conflicts :)

**Comment by fellipewurthmann** [comment]
> Please resolve the conflicts :)

**Comment by fellipewurthmann** [comment]
done!

**Pull request merged**
