### PR TITLE
Add Transit Gateway Attachment icon, its alias and Internet Gateway alias.

### PR DESCRIPTION
**Pull request by laiminhtrung1997**

### CODE REVIEW

**Comment by gabriel-tessier** [comment]
Thank you for the PR, 
First as stated in the contributing file the icon must be maximum 256px, yours is 48, and also you need to run autogen script.
About adding alias refer to the #update-aliases section of the contributing file.

You can read all the details about here: about the https://github.com/mingrammer/diagrams/blob/master/CONTRIBUTING.md

**Comment by laiminhtrung1997** [comment]
Dear @gabriel-tessier,

First, I appreciate you taking the time to review my contribution.

I’ve implemented your recommendations: I updated the image and ran the autogen script. However, it generated a few additional changes. Should I remove these, or would it be better to add a new commit for them? Or should I leave them as is?

Could you please review it again when you have a moment?

Thank you very much!

**Comment by laiminhtrung1997** [comment]
@gabriel-tessier 

I removed unrelated files. Please have a look again. Thank you.

**Review by gabriel-tessier — APPROVED** [review]

**Review by tvqphuoc01 — APPROVED** [review]
LGTM

**Pull request merged**
