### PR TITLE
Add: Litmus Chaos and Chaos Mess for chaos engineering

### PR DESCRIPTION
**Pull request by nlamirault**
Signed-off-by: Nicolas Lamirault <nicolas.lamirault@gmail.com>

### CODE REVIEW

**Review by mingrammer — COMMENTED** [review]
I think these tools are for k8s. Right?

**Comment by nlamirault** [comment]
Yes.
i was hesitant to put chaos in kubernetes actually.

**Comment by mingrammer** [comment]
Hm, which do you think better for these among `onprem.chaos`, `k8s.ecosystem`, or new `cloudnative.chaos`?

**Comment by nlamirault** [comment]
@mingrammer why not `cloudnative.chaos` :+1:

**Comment by wolfspyre** [comment]
I don't really know what I'm talking about here, so take my input well salted; but I personally think chaos might fit better as a primary resource with the specific tools within the space contained within it.  Alternatively, it might fit better as a branch off of generic IE: `generic.chaos.obnoxiousPRCommenter` ;)

**Comment by mingrammer** [comment]
@wolfspyre But these tools are for `k8s` and cloud-native applications. So I think `cloudnative.chaos` or `k8s.ecosystem` might be better for these.

**Review by mingrammer — CHANGES_REQUESTED** [review]
Please re-run the autogen to add cloudnative provider.

**Comment by nlamirault** [comment]
@mingrammer done.

**Comment by mingrammer** [comment]
@nlamirault Ah, since the `cloudnative` is a new provider, you need to do some extra work to support a new provider. 

You should add the `cloudnative` to [config.py](https://github.com/mingrammer/diagrams/blob/master/config.py#L14), and add the some functions for `cloudnative` to [resource.py](https://github.com/mingrammer/diagrams/blob/master/scripts/resource.py).

Sorry for that there is no guideline for adding a new provider, I'll add a guideline for this.

**Comment by mingrammer** [comment]
@nlamirault Wait .. hmm we need to re-discuss about which provider is suitable for these tools. `Jaeger` is also cloud native projet, but it could be under the `onprem` provider, so I think `cloudnative` provider could be getting a little vague. wdyt?

**Comment by nlamirault** [comment]
@mingrammer LitmusChaos and ChaosMesh are for Kubernetes. So,  why not `k8s.chaos` like `k8s.ecosystem` is for Kubernetes tools.

**Comment by mingrammer** [comment]
@nlamirault `k8s.chaos` sounds good  to me.

**Comment by nlamirault** [comment]
@mingrammer Done.

**Review by mingrammer — APPROVED** [review]
LGTM!

**Pull request merged**
