### PR TITLE
Support attributes on custom node

### PR DESCRIPTION
**Pull request by eksop**
This fixes problem when trying to use `pin`, `pos`, etc with custom nodes

### CODE REVIEW

**Review by peytondmurray — APPROVED** [review]
This looks good to me - I implemented something similar before finding this, and it seems to work well.

**Comment by pihart** [comment]
Any reason why this hasn't been merged?

**Comment by markthompson94** [comment]
Could this be merged please? :)

**Comment by sabedevops** [comment]
Please merge this PR, it's very much needed.

**Comment by dvanbolt** [comment]
Please merge this

**Comment by ThomasKat** [comment]
Please merge this

**Comment by mingrammer** [comment]
It is resolved by https://github.com/mingrammer/diagrams/pull/437.

**Comment by mingrammer** [comment]
I close it!

**Pull request closed without merging**
