### PR TITLE
Rename Cloudfront to CloudFront

### LINKED ISSUE #30: Typo CloudFront
CloudFront를 사용하려고 보니 오타가 있군요.

`aws.network.Cloudfront` > `aws.network.CloudFront`로 바껴야됩니다.

https://github.com/mingrammer/diagrams/blob/master/diagrams/aws/network.py#L27

### PR DESCRIPTION
**Pull request by skmatz**
Fix #30.

### CODE REVIEW

**Comment by mingrammer** [comment]
Thank you for correcting it. But, do not edit the node class files by yourself.

Please use the auto-generation script. You can add the cloudfront to `TITLE_WORDS` map (https://github.com/mingrammer/diagrams/blob/master/config.py#L60) and just run the `autogen.sh`

Contributing guideline reference: https://github.com/mingrammer/diagrams/blob/master/CONTRIBUTING.md

**Comment by gabriel-tessier** [comment]
@mingrammer I gave a try on my fork by just updating the config.py file, I'm a little bite confuse as I was expecting that it will update everywhere but look like it only update the alias do I need to also update the name of the class and the file?
If you can give more details so this long pending issues can be closed.
There's a link in the original issue:
https://github.com/mingrammer/diagrams/issues/30
Or directly in my commit on my fork:
https://github.com/gabriel-tessier/diagrams/commit/b18a909d817bb9dedc8a79074165ad6e2227142e

I'll make a clean PR when it's ok.

m(__)m

**Comment by skmatz** [comment]
@mingrammer

Thanks for your contribution.
Also, I'm sorry for putting the pull request on hold.
I've tried it before, but it didn't work as expected like you, so I hope you can fix it instead.

**Comment by mingrammer** [comment]
@gabriel-tessier You should also add the `CloudFront` to [`TITLE_WORDS` map](https://github.com/mingrammer/diagrams/blob/master/config.py#L60), then run the `autogen.sh` to update the node class.

**Comment by rickhull** [comment]
I believe this PR is now moot

**Pull request closed without merging**
