### PR TITLE
Add GitlabCI to onprem.ci section

### PR DESCRIPTION
**Pull request by tongpu**

### CODE REVIEW

**Comment by mingrammer** [comment]
The logo only image would be better. WDYT?

**Comment by tongpu** [comment]
I was thinking to use the CI/CD logo to differentiate it from the logo used for GitLab the git service, but I'm going to replace it with the logo only version.

**Comment by mingrammer** [comment]
@tongpu Oh, that makes sense. I accepted it.

**Comment by mingrammer** [comment]
You don't need to replace it with logo the only image. I'll merge it as is.

**Pull request merged**
