### PR TITLE
Add diagrams.onprem.network.Mikrotik

### PR DESCRIPTION
**Pull request by nobiit**
Added Mikrotik as it is also quite popular
Website: https://mikrotik.com/

### CODE REVIEW

**Comment by nobiit** [comment]
image

```
from diagrams import Diagram
from diagrams.onprem.network import Pfsense, Mikrotik
from diagrams.onprem.proxmox import ProxmoxVE

with Diagram('Network', show=False):
    nfg1 = Pfsense('nfg1')
    nrg1 = Mikrotik('nrg1')

    nfg1 >> nrg1 >> [ProxmoxVE('v1'), ProxmoxVE('v2'), ProxmoxVE('v3')]
```

**Comment by gabriel-tessier** [comment]
@nobiit 
Thanks for the PR, 

The logo you submitted is different than the one on their website.
There's a list and instructions on their page: https://mikrotik.com/logo

Also check the instructions about the icon size here: about the https://github.com/mingrammer/diagrams/blob/master/CONTRIBUTING.md

**Comment by nobiit** [comment]
image

**Comment by nobiit** [comment]
I changed the logo to exactly 256px, thanks for the advice

**Review by tvqphuoc01 — APPROVED** [review]

**Pull request merged**
