### PR TITLE
Updated + Added extra Elastic icons

### PR DESCRIPTION
**Pull request by jamesagarside**
Add and Update Elastic icons: Delivers issue: #756

### CODE REVIEW

**Comment by jamesagarside** [comment]
@mingrammer brilliant project, thank you for getting this going! 
What is your approval process for pull requests, keen to get this merged so I can start using the additions in my designs :)

**Comment by jamesagarside** [comment]
@mingrammer any luck on this getting merged please? 

I work at Elastic and use this project for some designs

**Review by mingrammer — APPROVED** [review]
LGTM!!

**Comment by mingrammer** [comment]
@jamesagarside Sorry for the late review. Great improvments. Please resolve the conflicts.

**Comment by mingrammer** [comment]
Closes #756 .

**Comment by mingrammer** [comment]
There are too many file changes. @jamesagarside Could you please fix it or re-open the PR? 🙏

**Comment by mingrammer** [comment]
I'll update the master with latest autogenerated files. Wait a minute please.

**Comment by mingrammer** [comment]
@jamesagarside I fixed some resource gen issues. Please merge the master and re-run the autogen script.

**Comment by jamesagarside** [comment]
@mingrammer directory removed. Apologies

**Comment by jamesagarside** [comment]
@mingrammer Fixed :D

**Review by mingrammer — APPROVED** [review]
LGTM!!

**Pull request merged**
