### PR TITLE
Add digdag

### PR DESCRIPTION
**Pull request by yu-iskw**
## Digdag
Digdag is a simple tool that helps you to build, run, schedule, and monitor complex pipelines of tasks. It handles dependency resolution so that tasks run in series or in parallel.
Digdag replaces cron, facilitates IT operations automation, orchestrates data engineering tasks, coordinates machine learning pipelines, and more.
https://www.digdag.io/

### CODE REVIEW

**Comment by mingrammer** [comment]
How about the icon only image for digdag? I found that one: https://docs.digdag.io/_static/logo/dig-dag-logo-tr.png

**Comment by yu-iskw** [comment]
It looks good! I will change.

**Comment by mingrammer** [comment]
Thank you

**Comment by yu-iskw** [comment]
Thank you for merging it!

**Pull request merged**
