### PR TITLE
Add: GCP monitoring

### PR DESCRIPTION
**Pull request by pyaillet**
Add an icon for GCP Monitoring solving #315

### CODE REVIEW

**Comment by tanjinP** [comment]
@pyaillet instead of `management` do you think it's better to call it `operations`? - [as per their documentation](https://cloud.google.com/products/operations)

**Comment by pyaillet** [comment]
> @pyaillet instead of `management` do you think it's better to call it `operations`? - [as per their documentation](https://cloud.google.com/products/operations)

✅ Done !
Thanks for the review :)

**Review by mingrammer — APPROVED** [review]
LGTM!

**Comment by mingrammer** [comment]
@tanjinP Good point. Thanks for the review.

**Pull request merged**
