### PR TITLE
add resource for bind9

### PR DESCRIPTION
**Pull request by nrvale0**

### CODE REVIEW

**Comment by mingrammer** [comment]
It doesn't seem to have been added via `autogen.sh`. There is no documentation update. Please add it with `autogen.sh`.

**Comment by nrvale0** [comment]
I followed the CONTRIBUTING.md. What is missing so I know how to verify proper addition? thx.

**Comment by mingrammer** [comment]
`autogen.sh` also update the documentation (`docs/nodes/onprem.md`) automatically. But there are no docs updates.

**Comment by nrvale0** [comment]
okthx. Will take a look...

**Comment by nrvale0** [comment]
When I ran autogen.sh is regenerated the onprem.md file -- looks like completely regenerated -- and all of the other doc files. I'll add the onprem.md to the PR (but not the other doc files) so you can see what I'm talking about and let me know if that is expected/desired result.

**Comment by mingrammer** [comment]
You must resolve the conflicts first :)

**Pull request closed without merging**
