### PR TITLE
Add PFSense and VyOS router distribution logos

### PR DESCRIPTION
**Pull request by avanier**
As title suggests, this adds the [PFSense][pfsense] and [VyOS][vyos] router distribution logos.

[pfsense]: https://www.pfsense.org/
[vyos]: https://www.vyos.io/

### CODE REVIEW

**Comment by avanier** [comment]
For some reason `black` wants to add a massive amount of line returns to `diagrams/onprem/network.py` on my computer. May I ask you run `autogen.sh` for me?

**Comment by mingrammer** [comment]
Yes, I can do that for you :). Before that, could you please resize the logos as `256x256`, `256x<height>` or `<width>x256` dimesions?

**Comment by avanier** [comment]
All done! I also submitted #72 to document the resizing thing. :muscle:

**Comment by mingrammer** [comment]
Thank you for contributing :)

**Pull request merged**
