### PR TITLE
Add Cloud IAP (Identity-Aware Proxy)

### LINKED ISSUE #33: Feature - add GCP IAP (Identity Aware Proxy)
Please add GCP IAP (Identity Aware Proxy) Node.

### PR DESCRIPTION
**Pull request by pshevtsov**
Fixes #33

### CODE REVIEW

**Comment by mingrammer** [comment]
Hmm .. duplicate of #43

**Comment by pshevtsov** [comment]
@mingrammer Yes, but this one is with proper icon.

**Comment by mingrammer** [comment]
Ok, but since @McSly contributed first for this, what do you think of adding @McSly as a co-author to this commit?

Do you mind if I do this, @McSly? :)

**Comment by pshevtsov** [comment]
I don't mind at all. I just need that icon :smile:

**Comment by McSly** [comment]
Either option is fine with me. Sorry I didn't have time to complete the previous pull request

**Comment by mingrammer** [comment]
Thank you guys :)

**Pull request merged**
