### PR TITLE
Add ZuulCI as onprem CI resource

### PR DESCRIPTION
**Pull request by y2kenny**
Zuul is an open source program that drives continuous integration,
delivery, and deployment systems with a focus on project gating and
interrelated projects.

https://zuul-ci.org/

### CODE REVIEW

**Comment by mingrammer** [comment]
It doesn't seem to have been generated via `autogen.sh`. Please run the `autogen.sh` to add the new node class.

**Comment by y2kenny** [comment]
> It doesn't seem to have been generated via `autogen.sh`. Please run the `autogen.sh` to add the new node class.

I tried running that but it pretty much touches every file in the repository (removing empty lines and other unrelated artifacts.)  Are you ok with that?

**Comment by y2kenny** [comment]
Actually... not every files but a few that don't look relevant.  Should I just pick and choose?

**Comment by mingrammer** [comment]
Don’t mind the changes. That might be due to unpredictable order of dict.

**Comment by mingrammer** [comment]
Could you please add `ZuulCI` alias in [`config.py`](https://github.com/mingrammer/diagrams/blob/master/config.py#L76)?

**Comment by y2kenny** [comment]
> Could you please add `ZuulCI` alias in [`config.py`](https://github.com/mingrammer/diagrams/blob/master/config.py#L76)?

Ok done.

**Pull request merged**
