### PR TITLE
fix: Refactor on-premises service names for consistency

### PR DESCRIPTION
**Pull request by filipeaaoliveira**
Summary:
This PR addresses the issue of incorrect usage of the term "premise" across the codebase and documentation. In all relevant instances, "premise" has been updated to "premises" to reflect the proper plural form.

Changes:
Replaced all instances of "premise" with "premises" in both code comments and documentation.

Rationale:
The term "premise" refers to a singular proposition or assumption, while "premises" is typically used when referring to a set of assumptions or statements, particularly in technical contexts. This correction improves the accuracy and professionalism of the codebase and documentation.

### CODE REVIEW

**Review by tvqphuoc01 — APPROVED** [review]
LGTM 👍

**Comment by gabriel-tessier** [comment]
@filipeaaoliveira

**Comment by filipeaaoliveira** [comment]
@gabriel-tessier This has been updated as well.

**Review by gabriel-tessier — CHANGES_REQUESTED** [review]
@filipeaaoliveira 
You added the changes in the 0.16.0 section, better to create a new section 0.23.5 on the top of the file with the changes.
In worst case if the PR don't ship in the next version we just need to update the version number after merge with master.

**Review by gabriel-tessier — APPROVED** [review]

**Comment by mingrammer** [comment]
Thank you guys!!

**Pull request merged**
