### PR TITLE
CONTRIBUTING.md improvements and generic fix

### PR DESCRIPTION
**Pull request by leandrodamascena**

### CODE REVIEW

**Comment by mingrammer** [comment]
`Resources with 2 to 4 characters words must be configured to use Uppercase` is not true, we enforce the using uppercase for only some acronym words or common initialisms such as RDS (Relational Database Service), VPN (Virtual Private Network), ML (Machine Learning) and so on. 
The `rack` is not this case, it should be `rack` as is, not `RACK` I think.

**Comment by leandrodamascena** [comment]
Ok.. I misunderstand the purpose of Uppercase, now I get it!

Do you want that I modify this text to describe in which situations Uppercase must be used?

**Comment by mingrammer** [comment]
Hm, I think that we don't need to force the uppercase words with `MUST BE` sentence. Code review would be enough for it :)

**Comment by leandrodamascena** [comment]
Ok. I'll close this PR @mingrammer!

Thank you and let's go to improve the project even more!

**Pull request closed without merging**
