### PR TITLE
Add: Tekton component

### PR DESCRIPTION
**Pull request by nlamirault**
Adding new CICD component: [tekton](https://tekton.dev/)

### CODE REVIEW

**Comment by mingrammer** [comment]
It doesn't seem to have been generated via `autogen.sh`. Please run the `autogen.sh` to add the new node class.

**Comment by nlamirault** [comment]
@mingrammer i add Tekton as a CD component, but it could be CI too.

**Comment by mingrammer** [comment]
Please resolve the conflicts :)

**Comment by nlamirault** [comment]
@mingrammer done.

**Pull request merged**
