### PR TITLE
added nextcloud, bitwarden, boundary and ambassador

### PR DESCRIPTION
**Pull request by tbrtje**

### CODE REVIEW

**Comment by tbrtje** [comment]
I would like to know as well. If there isnt any interest in integrating more things, it should be mentioned in the readme.

**Comment by wolfspyre** [comment]
near as i can tell, It’s not a reticence to add new things so much as mingrammer’s busy and doesn’t have much curation help here.. 

patience, persistence, compassion, persistence, empathy, persistence, and patience seems to be the successful tactic here :) ;)

**Review by mingrammer — APPROVED** [review]
LGTM. Sorry for the late. Thank you.

**Comment by Hkyx** [comment]
look to use Ambassador but got problem with it:
```
from diagrams import Cluster, Diagram, Edge
from diagrams.onprem.network import Ambassador
from diagrams.onprem.monitoring import Grafana, Prometheus
# from diagrams.onprem.logging import Fluentd

with Diagram(name="Office-Protect", show=True):
    with Cluster("Kubernetes"):
        ingress = Ambassador("Ambassador Ingress")
        metrics = Prometheus("Prometheus")
        dashboardmetrics = Grafana("monitoring")

        ingress >> metrics << Edge(color="firebrick", style="dashed") << dashboardmetrics
```


`
[15373:15373:0215/150009.865958:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
/usr/bin/python /home/hk/workspace/sherweb/architecture/op/main.py
Traceback (most recent call last):
  File "/home/hk/workspace/sherweb/architecture/op/main.py", line 2, in <module>
    from diagrams.onprem.network import Ambassador
ImportError: cannot import name 'Ambassador' from 'diagrams.onprem.network' (/home/user/.local/lib/python3.9/site-packages/diagrams/onprem/network.py)
`


Any idea?

**Comment by tbrtje** [comment]
Yeah, I've taken a look into the network.py of the pip package and it doesnt contain this commit yet. You should be able to install this package from the master branch with ```pip install git+https://github.com/mingrammer/diagrams.git```
Hope this helps :)

**Pull request merged**
